config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  resources :books
  resources :authors

  namespace :api do 
    namespace :v1 do 
      resources :authors
    end 
  end 

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_and_belongs_to_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_and_belongs_to_many :authors
end

app/controllers/api/v1/api_controller.rb
class ApiController < ActionController::Base
  # put any api-only filters and helpers here
end

app/controllers/api/v1/authors_controller.rb
# class Api::V1::AuthorsController < ApplicationController
class Api::V1::AuthorsController < ApplicationController
# class Api::Authors < Api::V1::ApiController
  def index
    @authors = Author.all
    render :json => {authors: @authors}
  end

  def show
    @author = Author.find(params[:id]) rescue "No author found with #{params[:id]} id"
    @books = @author=="No author found with #{params[:id]} id" ? "No books" :  @author.books
     render :json => {authors: @author, books: @books}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all.includes(:books)
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
    @books = Book.all
  end

  # GET /authors/1/edit
  def edit
    @books = Book.all
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)
    respond_to do |format|
      if @author.save
        update_author_books(@author, author_params)
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # for adding/updating books into authors
  def update_author_books(author, author_params)
    author.books.delete_all if author.books.present?
    params[:author][:book_ids].each do |book_id|
      book = Book.find(book_id) rescue ""
      author.books << book if book.present?
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        update_author_books(@author, author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:first_name, :last_name, :date_of_birth, :book_ids)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all.includes(:authors)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    @authors = Author.all
  end

  # GET /books/1/edit
  def edit
    @authors = Author.all
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        update_books_author(@book, book_params)
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # for adding/updating authors into books
  def update_books_author(book, book_params)
    book.authors.delete_all if book.authors.present?
    params[:book][:author_ids].each do |author_id|
      author = Author.find(author_id) rescue ""
      book.authors << author if author.present?
    end
  end 

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        update_books_author(@book, book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:book_title, :author_ids)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.text_field :date_of_birth %>
  </div>

  <div class="field">
    <%= f.label :books %><br>
    <%= f.collection_select(:book_ids, @books, :id, :book_title,
                                    {include_blank: true}, {multiple: true}) %> 
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Home', welcome_index_path %> || 
<%= link_to 'Books', books_path %>
<h1>Listing Authors</h1>

<% if @authors.present? %>
  <table>
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Date of birth</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @authors.each do |author| %>
        <tr>
          <td><%= author.first_name %></td>
          <td><%= author.last_name %></td>
          <td><%= author.date_of_birth %></td>
          <td><%= link_to 'Show', author %></td>
          <td><%= link_to 'Edit', edit_author_path(author) %></td>
          <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>
    <p> No author present, please add first to check the list! </p>
  <% end %>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @author.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @author.last_name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @author.date_of_birth %>
</p>

<hr>
<h3><%= "#{@author.first_name} #{@author.last_name} books" %></h3>
<% if @author.books.present? %>
	<table>
	  <thead>
	    <tr>
	      <th>book title</th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @author.books.each do |book| %>
	      <tr>
	        <td><%= book.book_title %></td>
	     </tr>
	    <% end %>
	  </tbody>
	</table>
<% else %>
  <p> no book present at this time, please try later! </p>
<% end %>

<br>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_title %><br>
    <%= f.text_field :book_title %>
  </div>

  <div class="field">
    <%= f.label :authors %><br>
    <%= f.collection_select(:author_ids, @authors, :id, :last_name,
                                    {include_blank: true}, {multiple: true}) %> 
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Home', welcome_index_path %> || 
<%= link_to 'Authors', authors_path %>

<h1>Listing Books</h1>
<% if @books.present? %>
  <table>
    <thead>
      <tr>
        <th>Book title</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.book_title %></td>
          <td><%= link_to 'Show', book %></td>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>
          <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
    <p> No book present, please add first to check the list! </p>
  <% end %>
<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book title:</strong>
  <%= @book.book_title %>
</p>

<hr>
<h3><%= "#{@book.book_title} authors" %></h3>
<% if @book.authors.present? %>
	<table>
	  <thead>
	    <tr>
	      <th>first name</th>
	      <th>last name</th>
	      <th>date of birth</th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @book.authors.each do |author| %>
	      <tr>
	        <td><%= author.first_name %></td>
	        <td><%= author.last_name %></td>
	        <td><%= author.date_of_birth %></td>
	     </tr>
	    <% end %>
	  </tbody>
	</table>
<% else %>
  <p> no author present at this time, please try later! </p>
<% end %>


<br>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BooksDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Books Demo!</h1>


<%= link_to 'Books', books_path %>  || 
<%= link_to 'Authors', authors_path %>